language: node_js

node_js:
  - "4.1"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

before_script:
  - npm install -g bower purescript
  - bower install

script:
  gulp test

sudo: false
