language: node_js

node_js:
  - "4.1"

before_install:
- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
- sudo apt-get update -qq

install:
- sudo apt-get install -qq g++-4.8
- export CXX="g++-4.8"

before_script:
  - npm install -g bower purescript
  - bower install

script:
  gulp test

sudo: required
